### PR TITLE
#131356219 Effective UI/UX Landing page

### PR DESCRIPTION
**Pull request by andela-foladeji**
#### What does this PR do?

Gives the landing page a new look that is more intuitive and appealing to users
#### Description of Task to be completed?

Users should be able to see an overview of what the game is about, how it's played and how it can be used to donate to charity and also see call to action buttons that lead them to signup or signin
#### How should this be manually tested?

https://hyuga-cfh-staging-pr-29.herokuapp.com/
#### Any background context you want to provide?

NA
#### What are the relevant pivotal tracker stories?
# 131356219 Users should see a landing page with effective UI/UX
#### Screenshots (if appropriate)

image
#### Questions:

NA

### CODE REVIEW

**Comment by azemoh** [comment]
Hey @andela-foladeji the CSS on our game page is broken.
screen shot 2016-10-28 at 9 03 16 am

**Comment by andela-cnwankwo** [comment]
Clicking on signup/login button on the top right of the landing page redirects to the signup page. How can users access the login page?

**Comment by andela-foladeji** [comment]
@azemoh, the css on the game page has been fixed
@andela-cnwankwo, the sign in link has been added to the menu

**Comment by azemoh** [comment]
LGTM

**Pull request merged**
